replicaCount: 2

ingress:
  hosts:
    - host: inventory-staging.workshop.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
