replicaCount: 1

ingress:
  hosts:
    - host: inventory-dev.workshop.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
