"""Report generation module - produces structured Markdown research reports."""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

from analyzer import AnalysisResult
from config import OutputConfig


class ReportGenerator:
    """Generates comprehensive Markdown research reports."""

    def __init__(self, config: OutputConfig | None = None) -> None:
        self.config = config or OutputConfig()
        Path(self.config.output_dir).mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        executive_summary: str,
        analyses: list[AnalysisResult],
        metadata: dict[str, str | int] | None = None,
    ) -> str:
        """Generate a full Markdown research report and write it to disk.

        Returns the file path of the generated report.
        """
        now = datetime.now(timezone.utc)
        timestamp = now.strftime("%Y-%m-%d_%H%M%S")
        filename = f"uk_retail_banking_research_{timestamp}.md"
        filepath = os.path.join(self.config.output_dir, filename)

        report_lines: list[str] = []

        # ----- Title & Metadata -----
        report_lines.append(
            "# UK Retail Banking & Cash Savings Research Report"
        )
        report_lines.append("")
        report_lines.append(
            f"**Generated:** {now.strftime('%d %B %Y at %H:%M UTC')}"
        )
        if metadata:
            if "sources_scraped" in metadata:
                report_lines.append(
                    f"**Sources Scraped:** {metadata['sources_scraped']}"
                )
            if "pages_analysed" in metadata:
                report_lines.append(
                    f"**Pages Analysed:** {metadata['pages_analysed']}"
                )
        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")

        # ----- Table of Contents -----
        report_lines.append("## Table of Contents")
        report_lines.append("")
        report_lines.append("1. [Executive Summary](#executive-summary)")
        for i, analysis in enumerate(analyses, start=2):
            anchor = analysis.topic.lower().replace(" ", "-").replace("&", "and")
            report_lines.append(f"{i}. [{analysis.topic}](#{anchor})")
        report_lines.append(
            f"{len(analyses) + 2}. [Sources & Methodology](#sources-and-methodology)"
        )
        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")

        # ----- Executive Summary -----
        report_lines.append("## Executive Summary")
        report_lines.append("")
        report_lines.append(executive_summary)
        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")

        # ----- Individual Analysis Sections -----
        for analysis in analyses:
            report_lines.append(f"## {analysis.topic}")
            report_lines.append("")
            report_lines.append(analysis.analysis)
            report_lines.append("")

            if analysis.key_findings:
                report_lines.append("### Key Findings")
                report_lines.append("")
                for finding in analysis.key_findings:
                    report_lines.append(f"- {finding}")
                report_lines.append("")

            if analysis.sources_used:
                report_lines.append(
                    f"*Sources: {', '.join(analysis.sources_used)}*"
                )
                report_lines.append("")

            report_lines.append("---")
            report_lines.append("")

        # ----- Sources & Methodology -----
        report_lines.append("## Sources and Methodology")
        report_lines.append("")
        report_lines.append(
            "This report was generated by an automated research agent that:"
        )
        report_lines.append("")
        report_lines.append(
            "1. **Scraped** publicly available UK financial data sources using "
            "headless Selenium and HTTP requests"
        )
        report_lines.append(
            "2. **Extracted** structured data including rates, headlines, "
            "regulatory updates, and market insights"
        )
        report_lines.append(
            "3. **Analysed** the collected data using the Infosys AI Gateway "
            "LLM to produce structured insights"
        )
        report_lines.append(
            "4. **Compiled** findings into this comprehensive research report"
        )
        report_lines.append("")
        report_lines.append("### Data Sources")
        report_lines.append("")

        all_sources: set[str] = set()
        for analysis in analyses:
            all_sources.update(analysis.sources_used)
        for source in sorted(all_sources):
            report_lines.append(f"- {source}")
        report_lines.append("")

        report_lines.append("### Disclaimer")
        report_lines.append("")
        report_lines.append(
            "> This report is generated from publicly available information and "
            "LLM-based analysis. While every effort is made to ensure accuracy, "
            "the data should be independently verified before making financial "
            "decisions. Rates and product details change frequently; always check "
            "with providers directly for the latest information."
        )
        report_lines.append("")

        # ----- Write to file -----
        report_content = "\n".join(report_lines)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)

        return filepath
