apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-service.fullname" . }}-config
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env | default (list) | toJson | quote }}
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
