apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-service.fullname" . }}-db
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data:
  connection-string: {{ .Values.dbConnectionString | default "" | b64enc | quote }}
