<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ProductService/ProductService.csproj" />
    <ProjectReference Include="../../src/CustomerService/CustomerService.csproj" />
    <ProjectReference Include="../../src/InventoryService/InventoryService.csproj" />
    <ProjectReference Include="../../src/OrderService/OrderService.csproj" />
    <ProjectReference Include="../../src/ApiGateway/ApiGateway.csproj" />
  </ItemGroup>

</Project>
